public class Test {
    public static void main(String[] args){}

        

    public static void I_HATE_JAVA(){
        System.out.println("IHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVAIHATEJAVA");
    }
}
